# Generated by Django 5.0.6 on 2024-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_city_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='00000', max_length=6),
        ),
    ]
