# Generated by Django 5.0.6 on 2024-06-20 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_name', models.CharField(max_length=50)),
                ('to_phone', models.CharField(max_length=15)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_address', models.TextField()),
                ('to_zipcode', models.CharField(default='00000', max_length=6)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL)),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='administration.city')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='administration.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
